version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: hrms-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - hrms_data:/var/lib/postgresql/data
    networks:
      - hrms-network

volumes:
  hrms_data:

networks:
  hrms-network:
    driver: bridge
