spring:
  application:
    name: hr-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
  main:
    banner-mode: off

server:
  port: 8081

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.context: debug
    org.springframework.security: debug

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}